# Assignment 1 NumPy



In [6]:
#Import the libraries 
import numpy as np

# Problem 1 
Matrix Manipulations

Lets first create a matrix and perform some manipulations of it.

Using numpy's matrix data structure, define the following matricies:

$$A=\left[ \begin{array}{ccc} 3 & 5 & 9 \\ 3 & 3 & 4 \\ 5 & 9 & 17 \end{array} \right]$$

$$B=\left[ \begin{array}{c} 2 \\ 1 \\ 4 \end{array} \right]$$

After this solve the matrix equation:
$$Ax = B$$

In [5]:
a = np.array([[3, 5, 9], [3, 3, 4], [5, 9, 17]])
print(a)
b = np.array([[2], [1], [4]])
print(b)
x = np.linalg.solve(a, b)
m3 = np.dot(a,x) 
print(m3)

[[ 3  5  9]
 [ 3  3  4]
 [ 5  9 17]]
[[2]
 [1]
 [4]]
[[2.]
 [1.]
 [4.]]


# Problem 2
Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
Input: $$arrayOne = \left[\begin{array}{ccc} 5& 6& 9\\ 21 & 18 & 27\end{array}\right]$$
       $$arrayTwo = \left[\begin{array}{ccc} 15 &33& 24\\ 4 &7& 1\end{array}\right]$$



In [4]:
M1 = np.array([[5, 6, 9], [21, 18, 27]])
M2 = np.array([[15, 33, 24], [4, 7, 1]])
M3 = M1+M2
print(M3)
sqd = [[elem*elem for elem in inner] for inner in M3]
print('square of each element',sqd)

[[20 39 33]
 [25 25 28]]
square of each element [[400, 1521, 1089], [625, 625, 784]]


# Problem 3
Print max from axis 0 and min from axis 1 from the following 2-D array.\
$$sampleArray = \left[\begin{array}{ccc} 34&43&73 \\ 82&22&12 \\ 53&94&66 \end{array}\right]$$




In [3]:
print("Printing Original array")
M1 = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (M1)

minOfAxisOne = np.amin(M1, 1) 
print("Printing amin Of Axis 1")
print(minOfAxisOne)

maxOfAxisOne = np.amax(M1, 0) 
print("Printing amax Of Axis 0")
print(maxOfAxisOne)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing amin Of Axis 1
[34 12 53]
Printing amax Of Axis 0
[82 94 73]


# Problem 4
Get the positions where elements of a and b match\
Input:  a = np.array([1,2,3,2,3,4,3,4,5,6])\
b = np.array([7,2,10,2,7,4,9,4,9,8])\
Desired Output: array([1, 3, 5, 7])

In [2]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.arange(len(a))[a==b])

[1 3 5 7]


# Problem 5
Given 
$$a= \left[\begin{array}{cc} 1&2\\ 3&4 \end{array}\right]$$
$$b = \left[\begin{array}{cc} 5&6 \\ 7&8 \end{array}\right]$$
Obtain c and d
$$c = \left[\begin{array}{cc} 1&2\\ 3&4 \\ 5&6 \\ 7&8 \end{array}\right]$$
$$d = \left[\begin{array}{cccc} 1&2&5&6\\ 3&4&7&8 \end{array}\right]$$

In [7]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.append(a,b, 0)
print(c)
d = np.append(a,b, 1)
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
